services:
  mlflow:
    build:
      context: ./docker
      dockerfile: mlflow.Dockerfile
    image: local/mlflow:2.12.1
    container_name: mlflow-server
    ports:
      - "5001:5000"
    volumes:
      - ./mlflow.db:/mlflow.db
      - ./mlruns:/mlruns
    command: >
      server
      --backend-store-uri sqlite:////mlflow.db
      --default-artifact-root mlflow-artifacts:/
      --serve-artifacts
      --artifacts-destination file:/mlruns
      --host 0.0.0.0
      --port 5000
    restart: unless-stopped
